name: Build and Publish Tag
on:
  push:
    tags:
      - 'v*' # When code is pushed to any tag
jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.7
        with:
          gradle-version: wrapper
          arguments: build publish
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}
          TKLIB_PUBLISH_URL: ${{ secrets.MAVEN_PUBLISH_URL }}
          TKLIB_PUBLISH_USER: ${{ secrets.MAVEN_PUBLISH_USER }}
          TKLIB_PUBLISH_PASS: ${{ secrets.MAVEN_PUBLISH_PASS }}
          TKLIB_RELEASE: true
      - name: Create Release With Changelog
        uses: fregante/release-with-changelog@v3
        id: create_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-template: '- {title} ({hash})'
          template: |
            ### Changelog
            {commits}
      - name: Upload Binaries
        uses: NBTX/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          targets: build/libs/**.jar
